#!/usr/bin/env bash
# ------------------------------------------------------------------------ *\
# mk/iwyu/genpass.iwyu.sh
# This file is part of GenPass.
#
# Copyright (C) 2026       David Bears <dbear4q@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------ */

outFile=mk/iwyu/genpass.iwyu
# copyright="Copyright (C) 2026       David Bears <dbear4q@gmail.com>"

privateHeaders=$(
  find include -regextype posix-extended -regex '.*/detail([/.].*)?' \
  | sed -e 's#^include/##'
)


if [ -z "$copyright" ]; then
  echo "error: no copyright line" >&2
  exit 2
fi
echo """\
# This file was automatically generated by mk/iwyu/genpass.iwyu.sh.
# ------------------------------------------------------------------------ *\\
# $outFile
# This file is part of GenPass.
#
# $copyright
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ------------------------------------------------------------------------ */
""" > $outFile

echo "[" >> $outFile
for private in $privateHeaders ; do
  includers=$(
    grep -Erle "^\\s*#\\s*include\\s+\"$private\"" \
      --include '*.hpp' --include '*.h' -- include \
    | sed -e 's#^include/##'
  )
  for includer in $includers ; do
    if echo "$privateHeaders" | grep -Fxqe "$includer" ; then
      visibility=private
    else
      visibility=public
    fi
    echo "{ include: [ <$private>, private, <$includer>, $visibility ] }," \
      >> $outFile
  done
done
echo "]" >> $outFile
